apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  abc: QUJD

---

apiVersion: v1
kind: Pod
metadata:
  name: pod-volume-secret
spec:
  containers:
  - name: nginx
    image: nginx
    env:
      - name: ABC
        valueFrom:
          secretKeyRef:
            name: my-secret
            key: abc

---

apiVersion: v1
kind: Pod
metadata:
  name: pod-env-secret
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: foo
      mountPath: "/secret"
      readOnly: true
  volumes:
  - name: foo
    secret:
      secretName: my-secret
