apiVersion: v1 
kind: Pod 
metadata: 
  name: with-node-affinity 
spec: 
  affinity: 
    nodeAffinity: 
      requiredDuringSchedulingIgnoredDuringExecution: 
        nodeSelectorTerms: 
        - matchExpressions: 
          - key: gpu 
            operator: In 
            values: 
            - nvidia-tesla 
      preferredDuringSchedulingIgnoredDuringExecution: 
      - weight: 1 
        preference: 
          matchExpressions: 
          - key: group 
            operator: In 
            values: 
            - ai 
  containers: 
  - name: web 
    image: nginx
